"""
HTML report builder for Fusarium root pipeline.

For each (experiment, timepoint/DAI), creates one combined HTML report with all plates:
  - summary table per plate
  - per-plate overview images: white-balanced, boxes, polygons
  - per-bbox metrics including lane assignment and MaxRGB intensity
  - lane infection summary from <experiment>_lane_summary.csv when available
"""

import csv
import html
import os
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np

from config import CLASS_DISPLAY_NAMES, EXPERIMENT_NAME, INPUT_HAS_EXPERIMENT_LEVEL, OUTPUT_ROOT

CSS = """
body{font-family:system-ui,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:0;background:#0b0d10;color:#e5eef5}
a{color:#80c7ff;text-decoration:none}.container{max-width:1320px;margin:0 auto;padding:24px}
.card{background:#141920;border:1px solid #202632;border-radius:16px;padding:16px;margin:16px 0;box-shadow:0 6px 16px rgba(0,0,0,.25)}
.h1{font-size:28px;margin:8px 0 16px}.h2{font-size:22px;margin:8px 0 12px;color:#b7c7d9}.h3{font-size:18px;margin:8px 0 8px;color:#9fb2c7}
.grid{display:grid;gap:12px;grid-template-columns:repeat(3,minmax(260px,1fr))}.imgbox{background:#0e1217;border:1px solid #1e2430;border-radius:12px;padding:8px;text-align:center}.imgbox img{max-width:100%;border-radius:8px}.caption{font-size:13px;color:#a7bdd6;margin-bottom:6px}
.table{width:100%;border-collapse:collapse;margin-top:8px}.table th,.table td{padding:8px;border-bottom:1px solid #263042;text-align:left;font-size:14px}.table th{color:#b7c7d9}.badge{display:inline-block;padding:2px 8px;border-radius:999px;background:#1f2b3a;border:1px solid #2a3a4f;color:#a7bdd6;font-size:12px}.footer{color:#93a8bd;font-size:12px;margin-top:24px}.kv{display:flex;flex-wrap:wrap;gap:12px}.kv div{background:#0f141a;border:1px solid #1f2a38;border-radius:8px;padding:8px 10px}.small{font-size:12px;color:#9fb2c7}details.card{padding:0}details.card summary{list-style:none;cursor:pointer;padding:16px}details.card summary::-webkit-details-marker{display:none}details.card[open] summary{border-bottom:1px solid #202632}.card-inner{padding:16px}.row-class-0 td{background:rgba(220,80,80,0.18)}.row-class-1 td{background:rgba(80,200,120,0.18)}.row-class--1 td{background:transparent}
@media(max-width:900px){.grid{grid-template-columns:1fr}}
"""

HTML_TEMPLATE = """
<!doctype html>
<html>
<head><meta charset="utf-8"><title>{title}</title><style>{css}</style></head>
<body><div class="container">
  <div class="h1">{title}</div>
  <div class="kv">
    <div><b>Experiment:</b> {experiment}</div>
    <div><b>Timepoint:</b> {timepoint}</div>
    <div><b>Plates:</b> {nplates}</div>
    <div><b>Object CSV:</b> <a href="{csv_rel}" target="_blank">download</a></div>
    {lane_csv_link}
  </div>

  <div class="card">
    <div class="h2">Plate summary</div>
    <table class="table"><thead><tr>
      <th>Plate</th><th>#Objects</th><th>Mean Fusarium MaxRGB</th><th>Median Fusarium</th><th>Max Fusarium</th>
    </tr></thead><tbody>{summary_rows}</tbody></table>
    <div class="h3">Experiment stats</div><div class="small">{exp_stats}</div>
  </div>

  {plate_blocks}
  <div class="footer">Generated by Fusarium root pipeline.</div>
</div></body></html>
"""


def _slugify(s: str) -> str:
    return "".join(ch if ch.isalnum() else "-" for ch in s)


def _stats_string(vals: List[float]) -> str:
    if not vals:
        return "No data."
    arr = np.asarray(vals, float)
    return (
        f"n={arr.size} · mean={arr.mean():.2f} · median={np.median(arr):.2f} · "
        f"std={arr.std(ddof=1) if arr.size > 1 else 0:.2f} · "
        f"p10={np.percentile(arr, 10):.2f} · p90={np.percentile(arr, 90):.2f} · "
        f"min={arr.min():.2f} · max={arr.max():.2f}"
    )


def _img(abs_path: str, rel_from: str, caption: str) -> str:
    if not abs_path or not os.path.exists(abs_path):
        return f"<div class='imgbox'><div class='caption'>{html.escape(caption)}</div><div class='small'>Missing image</div></div>"
    rel = os.path.relpath(abs_path, rel_from).replace("\\", "/")
    return (
        "<div class='imgbox'>"
        f"<div class='caption'>{html.escape(caption)}</div>"
        f"<a href='{rel}' target='_blank' rel='noopener'><img src='{rel}' loading='lazy'></a>"
        "</div>"
    )




def _class_label(class_id) -> str:
    try:
        return CLASS_DISPLAY_NAMES.get(int(class_id), str(class_id))
    except (TypeError, ValueError):
        return str(class_id)


def _summary_row(plate_id: str, n_boxes: int, mean_fus: float, med_fus: float, max_fus: float) -> str:
    plate_link = f"<a href='#plate-{_slugify(plate_id)}'>{html.escape(plate_id)}</a>"
    return f"<tr><td>{plate_link}</td><td>{n_boxes}</td><td>{mean_fus:.2f}</td><td>{med_fus:.2f}</td><td>{max_fus:.2f}</td></tr>"


def _bbox_row(row: dict) -> str:
    cls_id = row.get("class_id", -1)
    tr_class = f"row-class-{cls_id}"
    return (
        f"<tr class='{tr_class}'>"
        f"<td>{html.escape(str(row.get('bbox_index', '')))}</td>"
        f"<td>{html.escape(str(row.get('class_display_name') or _class_label(row.get('class_id', ''))))}</td>"
        f"<td>{row.get('lane_id', '')}</td>"
        f"<td>{row.get('polygon_area_px', '')}</td>"
        f"<td>{row.get('pixels_fusarium_infection', row.get('pixels_class0', ''))}</td>"
        f"<td>{row.get('pixels_root_tissue', row.get('pixels_class1', ''))}</td>"
        f"<td>{float(row.get('fusarium_severity_maxrgb_intensity', 0) or 0):.2f}</td>"
        f"<td>{float(row.get('fusarium_severity_maxrgb_red', 0) or 0):.2f}</td>"
        f"<td>{float(row.get('control_severity_maxrgb_intensity', 0) or 0):.2f}</td>"
        f"<td>{float(row.get('control_severity_maxrgb_red', 0) or 0):.2f}</td>"
        "</tr>"
    )


def _lane_row(row: dict) -> str:
    return (
        "<tr>"
        f"<td>{row.get('lane_id', '')}</td>"
        f"<td>{row.get('lane_polygon_count_total', '')}</td>"
        f"<td>{float(row.get('fusarium_infection_polygon_percent', row.get('class0_polygon_percent', 0)) or 0):.2f}</td>"
        f"<td>{float(row.get('fusarium_infection_area_percent', row.get('class0_area_percent', 0)) or 0):.2f}</td>"
        f"<td>{float(row.get('fusarium_infection_mean_maxrgb_intensity', row.get('class0_mean_maxrgb_intensity', 0)) or 0):.2f}</td>"
        f"<td>{float(row.get('fusarium_infection_mean_maxrgb_red', row.get('class0_mean_maxrgb_red', 0)) or 0):.2f}</td>"
        f"<td>{float(row.get('root_tissue_polygon_percent', row.get('class1_polygon_percent', 0)) or 0):.2f}</td>"
        f"<td>{float(row.get('root_tissue_area_percent', row.get('class1_area_percent', 0)) or 0):.2f}</td>"
        f"<td>{float(row.get('root_tissue_mean_maxrgb_intensity', row.get('class1_mean_maxrgb_intensity', 0)) or 0):.2f}</td>"
        f"<td>{float(row.get('root_tissue_mean_maxrgb_red', row.get('class1_mean_maxrgb_red', 0)) or 0):.2f}</td>"
        "</tr>"
    )


@dataclass
class PlateInfo:
    plate_id: str
    bbox_rows: List[dict] = field(default_factory=list)
    lane_rows: List[dict] = field(default_factory=list)
    path_wb: Optional[str] = None
    path_boxes: Optional[str] = None
    path_poly: Optional[str] = None

    @property
    def n_boxes(self) -> int:
        return len(self.bbox_rows)

    @property
    def fusarium_values(self) -> List[float]:
        vals = []
        for r in self.bbox_rows:
            try:
                v = float(r.get("fusarium_severity_maxrgb_intensity", 0.0))
            except (TypeError, ValueError):
                v = 0.0
            if v > 0:
                vals.append(v)
        return vals

    @property
    def fus_mean(self) -> float:
        vals = self.fusarium_values
        return float(np.mean(vals)) if vals else 0.0

    @property
    def fus_median(self) -> float:
        vals = self.fusarium_values
        return float(np.median(vals)) if vals else 0.0

    @property
    def fus_max(self) -> float:
        vals = self.fusarium_values
        return float(np.max(vals)) if vals else 0.0


def _load_lane_summary(lane_csv_path: Path) -> List[dict]:
    if not lane_csv_path.exists():
        return []
    with open(lane_csv_path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _build_experiment_timepoint_report(experiment: str, timepoint: str, rows: List[dict], csv_path: Path, output_root: Path) -> Path:
    if INPUT_HAS_EXPERIMENT_LEVEL:
        out_dir = output_root / experiment / timepoint
        plate_base_dir = output_root / experiment / timepoint
        lane_csv_path = output_root / experiment / f"{experiment}_lane_summary.csv"
    else:
        out_dir = output_root / timepoint
        plate_base_dir = output_root / timepoint
        lane_csv_path = output_root / f"{experiment}_lane_summary.csv"

    out_dir.mkdir(parents=True, exist_ok=True)
    title = f"Fusarium report · {experiment} · {timepoint}"
    lane_rows_all = [r for r in _load_lane_summary(lane_csv_path) if r.get("timepoint", "") == timepoint]

    plates: Dict[str, PlateInfo] = {}
    for r in rows:
        plate_id = r["plate_id"]
        stem = Path(r["image"]).stem
        if plate_id not in plates:
            plate_dir = plate_base_dir / plate_id
            plates[plate_id] = PlateInfo(
                plate_id=plate_id,
                path_wb=str(plate_dir / f"{stem}_wb.png"),
                path_boxes=str(plate_dir / f"{stem}_boxes.png"),
                path_poly=str(plate_dir / f"{stem}_poly.png"),
            )
        plates[plate_id].bbox_rows.append(r)

    for lr in lane_rows_all:
        plate_id = lr.get("plate_id", "")
        if plate_id in plates:
            plates[plate_id].lane_rows.append(lr)

    summary_rows_html = []
    all_fus_vals = []
    for plate_id in sorted(plates.keys()):
        p = plates[plate_id]
        all_fus_vals.extend(p.fusarium_values)
        summary_rows_html.append(_summary_row(plate_id, p.n_boxes, p.fus_mean, p.fus_median, p.fus_max))

    plate_blocks = []
    for plate_id in sorted(plates.keys()):
        p = plates[plate_id]
        imgs = "".join([
            _img(p.path_wb, str(out_dir), "White-balanced image"),
            _img(p.path_boxes, str(out_dir), "Bounding boxes"),
            _img(p.path_poly, str(out_dir), "Polygons"),
        ])

        bbox_rows_html = "".join(_bbox_row(r) for r in sorted(p.bbox_rows, key=lambda r: (int(r.get("lane_id", 0)), str(r.get("class_name", "")), int(r.get("bbox_index", 0)))))
        bbox_table = (
            "<table class='table'><thead><tr>"
            "<th>BBox #</th><th>Class</th><th>Lane</th><th>Area px</th>"
            "<th>px Fusarium infection</th><th>px Root tissue</th>"
            "<th>Fusarium MaxRGB intensity</th><th>Fusarium MaxRGB red</th>"
            "<th>Root MaxRGB intensity</th><th>Root MaxRGB red</th>"
            f"</tr></thead><tbody>{bbox_rows_html}</tbody></table>"
        )

        if p.lane_rows:
            lane_rows_html = "".join(_lane_row(r) for r in sorted(p.lane_rows, key=lambda r: int(float(r.get("lane_id", 0) or 0))))
            lane_table = (
                "<div class='h3'>Lane infection summary</div>"
                "<table class='table'><thead><tr>"
                "<th>Lane</th><th>#Objects</th>"
                "<th>Fusarium infection object %</th><th>Fusarium infection area %</th>"
                "<th>Fusarium MaxRGB intensity</th><th>Fusarium MaxRGB red</th>"
                "<th>Root tissue object %</th><th>Root tissue area %</th>"
                "<th>Root MaxRGB intensity</th><th>Root MaxRGB red</th>"
                f"</tr></thead><tbody>{lane_rows_html}</tbody></table>"
            )
        else:
            lane_table = "<div class='h3'>Lane infection summary</div><div class='small'>No lane summary available.</div>"

        block = f"""
<details class='card' id='plate-{_slugify(plate_id)}' open>
  <summary><div class='h2'>Plate {html.escape(plate_id)} <span class='badge'>{p.n_boxes} objects</span></div></summary>
  <div class='card-inner'>
    <div class='grid'>{imgs}</div>
    {lane_table}
    <div class='h3'>Per-object metrics</div>
    {bbox_table}
  </div>
</details>
"""
        plate_blocks.append(block)

    csv_rel = os.path.relpath(csv_path, out_dir).replace("\\", "/")
    lane_csv_link = ""
    if lane_csv_path.exists():
        lane_rel = os.path.relpath(lane_csv_path, out_dir).replace("\\", "/")
        lane_csv_link = f"<div><b>Lane CSV:</b> <a href='{lane_rel}' target='_blank'>download</a></div>"

    html_out = HTML_TEMPLATE.format(
        title=html.escape(title),
        css=CSS,
        experiment=html.escape(experiment),
        timepoint=html.escape(timepoint),
        nplates=len(plates),
        csv_rel=csv_rel,
        lane_csv_link=lane_csv_link,
        summary_rows="\n".join(summary_rows_html),
        exp_stats=html.escape(_stats_string(all_fus_vals)),
        plate_blocks="\n".join(plate_blocks),
    )

    out_path = out_dir / f"{experiment}_{timepoint}_all_plates_report.html"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html_out)
    print(f"  -> wrote HTML report: {out_path}")
    return out_path



def _build_report_index(experiment: str, report_paths: List[Path], output_root: Path) -> Path:
    """Create a simple overview page that links to all DAI/timepoint reports."""
    if INPUT_HAS_EXPERIMENT_LEVEL:
        index_dir = output_root / experiment
    else:
        index_dir = output_root
    index_dir.mkdir(parents=True, exist_ok=True)

    rows = []
    for report_path in sorted(report_paths, key=lambda p: str(p)):
        timepoint = report_path.parent.name
        rel = os.path.relpath(report_path, index_dir).replace("\\", "/")
        rows.append(
            f"<tr><td>{html.escape(timepoint)}</td>"
            f"<td><a href='{rel}' target='_blank'>Open all-plates report</a></td></tr>"
        )

    page = f"""<!doctype html>
<html>
<head>
<meta charset='utf-8'>
<title>{html.escape(experiment)} · Fusarium report index</title>
<style>{CSS}</style>
</head>
<body>
<div class='container'>
  <div class='h1'>🌾 Fusarium report index · {html.escape(experiment)}</div>
  <div class='card'>
    <div class='h2'>DAI / timepoint reports</div>
    <div class='small'>Each page contains all plates for the selected DAI/timepoint.</div>
    <table class='table'>
      <thead><tr><th>DAI / timepoint</th><th>Combined report</th></tr></thead>
      <tbody>{''.join(rows)}</tbody>
    </table>
  </div>
  <div class='footer'>Generated by FusVision Macro.</div>
</div>
</body>
</html>
"""
    out_path = index_dir / f"{experiment}_report_index.html"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(page)
    print(f"  -> wrote report index: {out_path}")
    return out_path


def _process_summary_csv(csv_path: Path, experiment: str, out_root: Path) -> None:
    print(f"\nProcessing experiment CSV: {csv_path}")
    rows_by_timepoint: Dict[str, List[dict]] = defaultdict(list)
    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            row["experiment"] = row.get("experiment", experiment)
            row["timepoint"] = row.get("timepoint", "")
            row["plate_id"] = row.get("plate_id", "")
            row["image"] = row.get("image", "")

            for key in ("bbox_index", "class_id", "pixels_class0", "pixels_class1", "pixels_fusarium_infection", "pixels_root_tissue", "lane_id", "polygon_area_px"):
                try:
                    row[key] = int(float(row.get(key, 0) or 0))
                except (TypeError, ValueError):
                    row[key] = 0

            for key in ("fusarium_severity_maxrgb_intensity", "fusarium_severity_maxrgb_red", "control_severity_maxrgb_intensity", "control_severity_maxrgb_red"):
                try:
                    row[key] = float(row.get(key, 0.0) or 0.0)
                except (TypeError, ValueError):
                    row[key] = 0.0

            rows_by_timepoint[row["timepoint"]].append(row)

    report_paths = []
    for timepoint, rows in sorted(rows_by_timepoint.items()):
        if rows:
            report_paths.append(_build_experiment_timepoint_report(experiment, timepoint, rows, csv_path, out_root))

    if report_paths:
        _build_report_index(experiment, report_paths, out_root)


def generate_html_reports(output_root: Optional[str] = None, fusarium_class_id: int = 0) -> None:
    """Scan OUTPUT_ROOT for experiment CSVs and build HTML reports."""
    if output_root is None:
        output_root = OUTPUT_ROOT
    out_root = Path(output_root)
    if not out_root.exists():
        print(f"OUTPUT_ROOT does not exist: {out_root}")
        return

    if INPUT_HAS_EXPERIMENT_LEVEL:
        for exp_dir in sorted(p for p in out_root.iterdir() if p.is_dir()):
            experiment = exp_dir.name
            csv_path = exp_dir / f"{experiment}_summary.csv"
            if csv_path.exists():
                _process_summary_csv(csv_path, experiment, out_root)
    else:
        csv_path = out_root / f"{EXPERIMENT_NAME}_summary.csv"
        if csv_path.exists():
            _process_summary_csv(csv_path, EXPERIMENT_NAME, out_root)
        else:
            for csv_path in sorted(out_root.glob("*_summary.csv")):
                if csv_path.name.endswith("_lane_summary.csv"):
                    continue
                experiment = csv_path.name.replace("_summary.csv", "")
                _process_summary_csv(csv_path, experiment, out_root)
